src/Entity/CarPool.php
<?php

namespace App\Entity;

use App\Repository\CarPoolRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CarPoolRepository::class)]
class CarPool
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    /**
    * @Assert\NotBlank
    */
    private $start_location;

    #[ORM\Column(type: 'string', length: 255)]
    /**
    * @Assert\NotBlank
    */
    private $stop_location;

    #[ORM\Column(type: 'datetime')]
    /**
    * @Assert\NotBlank
    */
    private $start_time;

    #[ORM\Column(type: 'datetime')]
    /**
    * @Assert\NotBlank
    */
    private $stop_time;

    #[ORM\Column(type: 'integer')]
    /**
    * @Assert\NotBlank
    */
    private $price;

    #[ORM\Column(type: 'integer')]
    /**
    * @Assert\NotBlank
    */
    private $user_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartLocation(): ?string
    {
        return $this->start_location;
    }

    public function setStartLocation(string $start_location): self
    {
        $this->start_location = $start_location;

        return $this;
    }

    public function getStopLocation(): ?string
    {
        return $this->stop_location;
    }

    public function setStopLocation(string $stop_location): self
    {
        $this->stop_location = $stop_location;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->start_time;
    }

    public function setStartTime(\DateTimeInterface $start_time): self
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getStopTime(): ?\DateTimeInterface
    {
        return $this->stop_time;
    }

    public function setStopTime(\DateTimeInterface $stop_time): self
    {
        $this->stop_time = $stop_time;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/CarPoolType.php
<?php

namespace App\Form;

use App\Entity\CarPool;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class CarPoolType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('start_location')
            ->add('stop_location')
            ->add('start_time')
            ->add('stop_time')
            ->add('price')
            ->add('user_id')
            ->add('save', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary float-end mb-2'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CarPool::class,
        ]);
    }
}

src/Controller/CarPoolController.php
<?php

namespace App\Controller;

use App\Entity\CarPool;
use App\Form\CarPoolType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CarPoolController extends AbstractController
{
    #[Route('/list', name: 'carpool-list')]
    public function list(ManagerRegistry $doctrine): Response
    {
        $carpools = $doctrine->getRepository(CarPool::class)->findAll();

        return $this->render('carpool/index.html.twig', [
            'carpools' => $carpools,
        ]);
    }

    #[Route('/trip/{carpool}', name: 'carpool-id')]
    public function show(CarPool $carpool): Response
    {
        return $this->render('carpool/show.html.twig', [
            'carpool' => $carpool,
        ]);
    }

    #[Route('/offer-seats', name: 'create')]
    public function create(Request $request, ManagerRegistry $doctrine): Response
    {
        // Creating a new CarPool
        $carpool = new CarPool();
        $form = $this->createForm(CarPoolType::class, $carpool);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            // Entity Manager
            $em = $doctrine->getManager();
            $em->persist($carpool);
            $em->flush();
            return $this->redirect($this->generateUrl('carpool-list'));
        }


        return $this->render('carpool/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/delete/{carpool}', name: 'delete')]
    public function delete(CarPool $carpool, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $em->remove($carpool);
        $em->flush();

        $this->addFlash('success', 'Your car pool has been removed');

        return $this->redirect($this->generateUrl('carpool-list'));
    }
}

templates/carpool/create.html.twig
{% extends "base.html.twig" %}

{% block body %}
	{{ form(form) }}{% endblock %}

templates/carpool/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	{% for message in app.flashes('success') %}
		<div class="alert alert-success">
			{{message}}
		</div>
	{% endfor %}
	<table class="table table-stripped">
		<thead>
			<tr>
				<td>Lieu de départ</td>
				<td>Lieu d'arrivée</td>
				<td>Départ</td>
				<td>Arrivée</td>
				<td>Prix</td>
				<td>Conducteur</td>
				<td>Actions</td>
			</tr>
		</thead>
		<tbody>
			{% for carpool in carpools %}
				<tr>
					<td>{{ carpool.startLocation }}</td>
					<td>{{ carpool.stopLocation }}</td>
					<td>{{ carpool.startTime|date('Y-m-d') }}</td>
					<td>{{ carpool.stopTime|date('Y-m-d') }}</td>
					<td>
						<a href="{{ path('carpool-id', { carpool: carpool.id }) }}">
							{{ carpool.price/100 }}€
						</a>
					</td>
					<td>{{ carpool.userId }}</td>
					<td>
						<a href="{{path('delete', { carpool: carpool.id })}}" class="text-danger">Remove</a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/carpool/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	{{ carpool.startTime|date('H:i') }}
	{{ carpool.startLocation }}
	=>
	{{ carpool.stopTime|date('H:i') }}
	{{ carpool.stopLocation }}<br/>
	{{ carpool.price / 100 }}
	€<br/>
	{{ carpool.userId }}
{% endblock %}